sudo: required
language: java
dist: trusty
jdk:
  - oraclejdk9
  - oraclejdk10


script:
  - mvn clean install

after_failure:
 - find ./ -type d -name "surefire-reports" -print0 | xargs -0 -I {} find {} -iname "*.txt" -type f | xargs cat
 - find . -type f -name "*.log" -print0 -exec cat {} \;
